language: ruby
rvm:
- 2.0.0
env:
  matrix:
    secure: Q2xdtMm3K13T+ayM1bxIx1iHp0bwdUvrxVi1RU6QSPqUmzb2Mb4UocL1ETu0QmglsCFamQPRoJQf0HeWn61KSIAhV+zOukEI/p3p8Aps2j+EzEVWZw7WHpR041CmgTaC0UWTRB0yz120T/Vb+DMSJQkgpKZgu3XOjeAhHt9bBtc=
