language: ruby
rvm:
- 2.0.0
env:
  TRAKT_API_KEY:
    secure: NJbyz0dL2skBZ933IjigyPTzCbb/2pCsyxfwKjkllwaTJVPYFesj1gR4TXL19JcHciVN6gDFninpaz3naZAtkJS3uzf3DbiDKS+ikZFdh9Wtt/OmrkQmRa4gEqafEUegBIF0lupML2zEE4oTavqLgjEavrtdBX7nETxHWIIcKyA=
