defaults: &defaults
  media_http_server: http://10.0.1.34/media
  movies_directory: /Volumes/Data/media/Movies
  tv_directory: /Volumes/Data/media/TV
  trakt_api_key: <Trakt API KEY>
  clean_token_list: SomeUnwantedToken SomeOtherUnwantedToken

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
